name: Auto-archive repository to Software Heritage when tags are pushed
on: 
  push:
    tags:
      - '*'

jobs:
  trigger_archival:
    name: Trigger archival on Software Heritage
    runs-on: ubuntu-20.04
    steps:
        - name: Run Software Heritage Save action
          uses: sdruskat/swh-save-action@v1.0.1
