name: Deploy release binaries and documentation
on: 
  push:
    tags:
      - '/^v\d+.\d+(.\d+)?(-\S*)?$/'

jobs:
  deploy_binaries:
    name: Deploy release binaries
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set JAVA_HOME to OpenJDK 8
          run: echo JAVA_HOME=$JAVA_HOME_8_X64 >> $GITHUB_ENV
        - name: Run Maven install (includes tests)
          run: xvfb-run mvn clean install
          env:
            LANG: en_US.UTF-8
        - name: Update CFF file
          run: mvn -f ./features/org.corpus_tools.hexatomic/pom.xml cff:create
          env:
            LANG: en_US.UTF-8
        - name: Build again with updated CFF file
          run: xvfb-run mvn clean verify
          env:
            LANG: en_US.UTF-8
        - name: Release assets on GitHub
          uses: softprops/action-gh-release@v0.1.5
          with:
            files: releng/org.corpus_tools.hexatomic.product/target/products/hexatomic-*.zip
            draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}